# Put this file in .github/workflows/ on your main branch
name: Build Flutter APK
on: 
  push:
    branches: [ main, flutter ]  # Triggers on pushes to main or flutter branch
  pull_request:
    branches: [ main, flutter ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout flutter branch
        uses: actions/checkout@v4
        with:
          ref: flutter  # This ensures it always checks out the flutter branch

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'  # This will automatically use the latest stable version

      - name: Disable analytics
        run: flutter config --no-analytics

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 30  # How long to keep the artifact
